name: Label if PR author is from this org

on:
  pull_request_target:
    types: [labeled]
  pull_request:

jobs:
  welcome:
    name: Welcome
    runs-on: ubuntu-latest
    steps:
      - name: Check if organization member
        id: is_organization_member
        uses: JamesSingleton/is-organization-member@1.0.0
        with:
          organization: SAP
          username: the-docta
          token: ${{ secrets.mytoken }}
      - name: If Belong
        if: steps.is_organization_member.outputs.result == 'true'
        run: echo User BELONGS to testorg
      - name: If Not Belong - Add Label
        if: steps.is_organization_member.outputs.result == 'false'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: Submitted by Guest
      - id: auth_gh
        name: Authenticate gh to repo
        run: echo -n ${{ secrets.mytoken }} | gh auth login --with-token

      - name: If Not Belong - Add Comment
        if: steps.is_organization_member.outputs.result == 'false'
        run: |
          printf "Add this note!" \
          | gh pr comment 7 --body-file -

      - name: Add Comment
        run: gh pr comment 7 --body "Thank you for opening this PR!"
        env:
            GITHUB_TOKEN: ${{ secrets.mytoken }}

      - name: Print Something
        run: |
          echo "${{ toJSON(github.event) }}"
          echo "${{ github.event.sender.login }}"
          echo "${{ github.event.issue.user.login }}"
      - name: add labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: stacked PR
