name: Is Organization Member Example

on:
  issues:
    types: [opened, labeled]

jobs:
  welcome:
    name: Welcome
    runs-on: ubuntu-latest
    steps:
      - name: Check if organization member
        id: is_organization_member
        uses: JamesSingleton/is-organization-member@1.0.0
        with:
          organization: SAP
          username: ${{ github.event.issue.user.login }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Comment FALSE
        if: steps.is_organization_member.outputs.result == true
        run: echo User BELONGS to testorg
      - name: Create Comment TRUE
        if: 1 == 1
        run: echo ${{ steps.is_organization_member.outputs.result }}
      - name: Print Something
        run: echo something to print out
