name: Is Organization Member Example

on:
  issues:
    types: [opened, labeled]

jobs:
  welcome:
    name: Welcome
    runs-on: ubuntu-latest
    steps:
      - name: Check if organization member
        id: is_organization_member
        uses: JamesSingleton/is-organization-member@1.0.0
        with:
          organization: SAP
          username: ${{ github.event.issue.user.login }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Comment FALSE
        if: steps.is_organization_member.outputs.result == 'true'
        run: echo User BELONGS to testorg
      - name: Create Comment TRUE
        if: steps.is_organization_member.outputs.result == 'false'
        run: echo "The selected color is ${{ steps.is_organization_member.outputs.result }}" 
      - name: Print Something
        run: |
          echo ${{ toJSON(github.event) }}
          echo ${{ github.event.issue.sender.login }}         
      - name: add labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: stacked PR
